### ISSUE TITLE
13) accessibility (pagination aria-label)

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#105]
In the pagination, the  « aria-label » attribute needs to be in the <a> rather than in the `<li>`

ex. https://data.asc-csa.gc.ca/dataset 
`<li aria-label="(current) Go to page 1" class="active"><a href="/dataset?page=1">1</a></li>`

N.B. the pagination is set in https://github.com/asc-csa/ckanext-asc-csa/blob/master/ckan/lib/helpers.py, starting at line 1345. This file must overwrite ckan/lib/helpers.py in vanilla CKAN in order to work properly.

**Comment by coleweusthem** [comment]
should be addressed by #107

**Comment by nfee006** [comment]
Confirmed.
