### ISSUE TITLE
14) Web Standards - issue with data-ajax-replace

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#106]
There is a « # » at the start of the URL of the « data-ajax-replace » attribute, which causes a JavaScript error. 

ex. https://data.asc-csa.gc.ca/dataset 
`<ul role="menu" aria-orientation="vertical" data-ajax-replace="#https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-en.html">`

N.B. the french alternative is https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-fr.html

**Comment by coleweusthem** [comment]
should be fixed with #107

**Comment by nfee006** [comment]
Confirmed.
