### ISSUE TITLE
Resource page - resource relationship is now mandatory?

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#125]
When you go to create a new resource or edit an existing one, you must now specify these two fields:

![image](https://user-images.githubusercontent.com/11013061/120372800-a404a800-c2e5-11eb-9baa-3dc7974f0888.png)

These shouldn't be mandatory. They weren't before, not sure when that snuck in.

**Comment by nfee006** [comment]
Same for Division on the dataset creation page 

![image](https://user-images.githubusercontent.com/11013061/120374172-39546c00-c2e7-11eb-9bd4-95628423ece2.png)

**Comment by coleweusthem** [comment]
@nfee006, can I move the json files for the scheming into the scheming plugin? I think I've got the this straightened out, but it doesn't make sense to me that it spread over 2 repositories

**Comment by nfee006** [comment]
@coleweusthem - go for it. Not quite sure why it was done that way in the first place.

**Comment by coleweusthem** [comment]
@nfee006, pushed the change, you'll need to fix the scheming settings in your config file:

scheming.dataset_schemas = ckanext.scheming:ckan_dataset.json  
 ckanext.csa:info.json ckanext.csa:doc.json
scheming.presets = ckanext.scheming:presets.json
 ckanext.fluent:presets.json

**Comment by nfee006** [comment]
Didn't break anything on my side and seems to have fixed the relationship type/related record issue/division issue.

These fields are now popping up as required as well (below). I cross-referenced with our prod server and the ones I've highlighted are not required there. Would it be possible to make them optional please? I worry that it may cause some issues when we migrate the metadata.  Thanks!

![image](https://user-images.githubusercontent.com/11013061/120668715-b81ee580-c45c-11eb-8066-23a4587fe037.png)

**Comment by coleweusthem** [comment]
@nfee006, I think i've got those optional now

**Comment by nfee006** [comment]
@coleweusthem looks great on my side. No other issues to flag for this.

**Comment by nfee006** [comment]
@emilinecsa Correct, this is fixed.
