### ISSUE TITLE
Question: documentation

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#128]
@coleweusthem : unless I'm misreading, I think you removed the instructions for installing vanilla CKAN from source (ie. for development). Was that intentional?

**Comment by coleweusthem** [comment]
Things changed for ckan 2.9, so I had updated it to follow the way I installed it. From what I can tell it gets installed in the same location as source did before, and it's actually a bit quicker and easier to follow. If theres some specific things I'm missing that you'd like to see let me know and I can certainly add sections.

**Comment by nfee006** [comment]
As long as we're 100% sure that we're not missing out on anything required for development. Since you installed it that way, I assume it's fine.

**Comment by nfee006** [comment]
@coleweusthem : can you add a section explaining how to implement the required changes in vanilla ckan (adding recline.js and pagination.py) please?

**Comment by nfee006** [comment]
Also, can you confirm that you're using nginx? We're not using it on our side - is there a benefit?

**Comment by coleweusthem** [comment]
@nfee006, I can add a section for that. and  to my knowledge apache and nginx are more or less interchangeable (I think you're use apache) I just used nginx because it was what ckan was recommending.

**Comment by nfee006** [comment]
@coleweusthem, did you get my email about demonstrating conformity?

**Comment by coleweusthem** [comment]
Yes, I'm, going to get that together today

**Comment by nfee006** [comment]
Sounds good! Wanted to make sure since emails have been buggy.

**Comment by nfee006** [comment]
Changes have been applied to the python3_updates branch.
