### ISSUE TITLE
Typo in page title(s)

### ISSUE THREAD

**Issue by spourdei** [asc-csa/ckanext-asc-csa#13]
"Canadian space agency" needs to be correctly capitalized across all templates in the English version. 

![image](https://user-images.githubusercontent.com/50145933/93610602-44ef4500-f99b-11ea-8619-2738a126b7de.png)

**Comment by J-bytes** [comment]
Already corrected on production server. Could be corrected on test server

**Comment by J-bytes** [comment]
An attempt to correct it through the web interface of ckan for the test server failed. I proposed that as long as the production server is not affected, we ignore this issue.

**Comment by J-bytes** [comment]
Changes pushed to master

**Comment by J-bytes** [comment]
just to be sure , it would be Canadian Space Agency | Agence spatiale canadienne right?

**Comment by J-bytes** [comment]
solved on master

**Comment by nfee006** [comment]
Verified on @ data.
