### ISSUE TITLE
Accessibility - API page error

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#130]
When I run the WAVE AIM validator on the site, I get the following error on the English API page (http://127.0.0.1:5000/en/API).

![image](https://user-images.githubusercontent.com/11013061/121901848-c5599100-ccf4-11eb-979d-3cb0d1c430b0.png)
![image](https://user-images.githubusercontent.com/11013061/121901888-cee2f900-ccf4-11eb-826f-1d6c445d71da.png)

@coleweusthem

**Comment by nfee006** [comment]
Same page with the IBM Equal Access Accessibility checker 
![image](https://user-images.githubusercontent.com/11013061/121903995-d1465280-ccf6-11eb-87ad-c1026da00829.png)

**Comment by coleweusthem** [comment]
working on this

**Comment by coleweusthem** [comment]
Some of the issues are from the GCweb theme, I took this screenshot from canada.ca's scan. So I'm working on correcting the issues that are exclusive to ckan. Updates to the GCWeb theme in the future should resolve the rest.
<img width="618" alt="Screen Shot 2021-06-14 at 1 21 42 PM" src="https://user-images.githubusercontent.com/46227765/121925594-77a05100-cd13-11eb-92c5-7640fef8c407.png">

**Comment by coleweusthem** [comment]
Looks like I've got all these minus the ones coming from gcweb
