### ISSUE TITLE
Accessibility - search page

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#131]
These are only being flagged by the IBM Equal Access Accessibility checkers, not by AIM. I assume they're required for WCAG conformity and not just bugs with the checker but let me know if not @coleweusthem 

![image](https://user-images.githubusercontent.com/11013061/121903711-8fb5a780-ccf6-11eb-867e-eb380ea4534e.png)
![image](https://user-images.githubusercontent.com/11013061/121903734-97754c00-ccf6-11eb-8700-3df5e514d737.png)

**Comment by coleweusthem** [comment]
looks like I've got all these except the ones from the gcweb theme
