### ISSUE TITLE
Accessibility - dataset page 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#132]
These are only being flagged by the IBM Equal Access Accessibility checkers, not by AIM. I assume they're required for WCAG conformity and not just bugs with the checker but let me know if not @coleweusthem 

![image](https://user-images.githubusercontent.com/11013061/121904375-21251980-ccf7-11eb-86eb-c66daf1beedc.png)

**Comment by coleweusthem** [comment]
looks like I've got all these except the ones from the gcweb theme
