### ISSUE TITLE
Dataset facet - low contrast and overflow 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#133]
![image](https://user-images.githubusercontent.com/11013061/127051764-2e408ac7-58cf-49a3-a8cd-977cde69ebad.png)

Stems from CKAN 2.9 main.css

**Comment by nfee006** [comment]
https://github.com/asc-csa/ckanext-asc-csa/pull/135
https://github.com/asc-csa/ckanext-asc-csa/pull/134

**Comment by nfee006** [comment]
Just need to figure out how to get the checkbox on the last activated filter to stay white without turning all visited links white. 

FYI @coleweusthem

**Comment by coleweusthem** [comment]
looks like you got this one figured out?

**Comment by nfee006** [comment]
Yep - good here. That should be it for the CKAN accessibility issues. Still the web standards ones to contend with though.

**Comment by coleweusthem** [comment]
@nfee006, can you let me know which of the CKAN issues are left? I'm looking for the ones I see in the email but looks like you might have corrected them.

**Comment by coleweusthem** [comment]
@nfee006, nvm, looks like the inspector might have been correcting the quotation issues, viewing the source shows them.

**Comment by nfee006** [comment]
I'll log them
