### ISSUE TITLE
Mistranslation & typo on the 404 page

### ISSUE THREAD

**Issue by spourdei** [asc-csa/ckanext-asc-csa#14]
When the user's language is set to french and they click "explorer> plus d'information" there is a section that returns text in English. (This was fixed although due to another issue the page returns a 404 error). 

The 404 error message also needs to be customized based on the user's language. 

![image](https://user-images.githubusercontent.com/50145933/93613249-9d741180-f99e-11ea-8696-0597b3c805f3.png)

**Comment by J-bytes** [comment]
Une nouvelle branche fut créée pour développer une page d'erreur alternative ....

**Comment by J-bytes** [comment]
The new branch created to solve thisproblem will show a translated error message. However, every error message will then be referred as 404 errors no matter what....

**Comment by nfee006** [comment]
Unable to replicate based on "explorer - plus d'information" directions but general 404 page for incorrect URLs is untranslated. 

![image](https://user-images.githubusercontent.com/11013061/101635905-976b5b00-39f8-11eb-9ee8-ec149b19726a.png)

**Comment by J-bytes** [comment]
@nfee006 A translation has been push to master to correct this issue. Can you confirm this?

**Comment by nfee006** [comment]
Seems good now. 

![image](https://user-images.githubusercontent.com/11013061/102540007-6fc16600-407c-11eb-8533-63ecab31f8ae.png)
