### ISSUE TITLE
API url in API readme

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/ckanext-asc-csa#146]
Update https://donnees-data.asc-csa.gc.ca/API so that https://open.canada.ca/data/en/api/3/action/organization_show?id=csa-asc&include_datasets=True points to http://donnees-data.asc-csa.gc.ca/api/3/action/organization_show?id=csa-asc&include_datasets=True (or best endpoint).

Code is still a good example for harvester... not for CSA CKAN.

**Comment by nfee006** [comment]
Resolved in #147. I will push it to prod first thing in the morning.
