### ISSUE TITLE
Formatting issue after recent patch/CKAN vanilla update

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#158]
Low priority, minor 

![image](https://github.com/asc-csa/ckanext-asc-csa/assets/11013061/e4722be8-5c92-4b3e-a47a-32b565b1b183)

This had been fixed in a previous iteration, but has sneaked back in since the recent patch/update. 

@emilinecsa ignore this while you're away, but for when you get back. Thanks!

**Comment by emilinecsa** [comment]
The [CSS issue](https://github.com/asc-csa/ckanext-asc-csa/issues/158) is now fixed on [QA](https://datatest.asc-csa.gc.ca/dataset/e0333ed6-a614-46b1-b595-1fac1ce9214a). I will deploy on the production server tomorrow morning.

To fix this issue, we simply define a the _word-break_ property of links:

```
a {
  color: #284162;
  word-break: break-all;
}
```

**Comment by emilinecsa** [comment]
The update was deployed on production.
