### ISSUE TITLE
Corrections Appliqués/Applied #12 – [Typo]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#16]
**Français:** 

En anglais, dans les sous-menus, il ne devrait pas y avoir des majuscules aux mots des titres ou sous-titres que sur la première lettre du premier mot, exemple Economics and Industry (industry devrait avoir une minuscule)…

En anglais, menu de gauche, section Collection type, mettre une minuscule à Spatial dans Non-Spatial
En anglais, menu de gauche, section Keywords, mettre une minuscule à Auditing dans Internal Auditing

Voir, http://13.88.240.170:8080/en/dataset

**English:**

In English, in the submenus, only the first letter of the first word should be capitalized in the titles and subtitles. Example: 'Economics and Industry' should instead be 'Economics and industry'

In English, section 'Collection Type', change Non-Spacial to Non-spatial
In English, section 'Keywords', change Internal Auditing to Internal auditing

See, http://13.88.240.170:8080/en/dataset

![download-1](https://user-images.githubusercontent.com/26583461/93625970-c00f2600-f9b0-11ea-8718-abfb3b1ddfa6.png)
![download](https://user-images.githubusercontent.com/26583461/93625971-c00f2600-f9b0-11ea-8bd3-d7eabf8cbac1.png)

**Comment by J-bytes** [comment]
Corrections partiellement appliqués. Les keyword sont des métadonnées importés de open canada. À ajouter dans le cleaning.

**Comment by J-bytes** [comment]
Tout devrait être corrigé excepté les mots-clés. Cela demanderait une correction manuelle sur chaque jeu de données.

**Comment by nfee006** [comment]
The "Internal auditing" tag was changed manually for each dataset affected. "Non-spatial data" was changed in usr/lib/ckan/default/src/ckanext-asc-csa/ckanext/csa/**preset.json**

![image](https://user-images.githubusercontent.com/11013061/101535970-5ecf7100-3967-11eb-8407-16ce32f76e78.png)

![image](https://user-images.githubusercontent.com/11013061/101536015-6bec6000-3967-11eb-84d5-6ab6c47495b2.png)

**Comment by alexaantoniazzi** [comment]
verified on @data
