### ISSUE TITLE
Corrections Appliqués/Applied #14 – [langue/language]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#17]
**Français:**

En français, à côté de Formats des ressources, on y retrouve "other"

Voir : http://data.asc-csa.gc.ca:8080/fr/dataset?page=4
(ex. fiche « Archive des données de WINDII »)

**English:** 

In French, beside the 'Formats des ressources:', the word 'other' appears 
See, http://data.asc-csa.gc.ca:8080/fr/dataset?page=4

![thumbnail_image006](https://user-images.githubusercontent.com/26583461/93626387-5a6f6980-f9b1-11ea-9e56-1341b859f92b.jpg)

**Comment by J-bytes** [comment]
corrigé sur master

**Comment by alexaantoniazzi** [comment]
Correction validée
