### ISSUE TITLE
Corrections Appliqués/Applied #18 – [typo]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#18]
**Français:**

Dans le Additional information, Homepage, on devrait y avoir un **s** à http://asc-csa.gc.ca...

Dans les 2 langues, dans une fiche, lorsqu'il y a un lien vers le site de l'Agence spatiale canadienne, il devrait y avoir un s à http, exemple: http://13.88.249.89:8080/dataset/ace42c4b-1f39-4fb2-b7ba-c500d06ed61e

Dans l'onglet Additional information, sous Homepage, il n'y a pas de s à l'hyperlien http://asc-csa.gc.ca/eng/publications/ae.asp
Voir http://13.88.240.170:8080/en/dataset/ace42c4b-1f39-4fb2-b7ba-c500d06ed61e

**English:**
In the Additional information, Homepage, we should have a link to http://asc-csa.gc.ca...

In both languages, there should be a plug, once there is one link to the CSA site. Example: http://13.88.249.89:8080/dataset/ace42c4b-1f39-4fb2-b7ba-c500d06ed61e

In the Additional information tab, under Homepage, there is no hyperlink to http://asc-csa.gc.ca/eng/publications/ae.asp

See http://13.88.240.170:8080/en/dataset/ace42c4b-1f39-4fb2-b7ba-c500d06ed61e

![download](https://user-images.githubusercontent.com/26583461/93627517-0ebdbf80-f9b3-11ea-8658-f5453fbb393e.png)

**Comment by J-bytes** [comment]
Cela se fait par un meilleur nettoyage des données. Soit par un script python ou manuellement par l'interface web de ckan

**Comment by nfee006** [comment]
Verified on @data.
