### ISSUE TITLE
Corrections No. 37 – [langue]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#23]
En français, si je fais une recherche, sous Aucun jeu de données trouvé, il est écrit en anglais "Please try another search." Il faudrait mettre en français.

Voir http://13.88.240.170:8080/fr/dataset?q=kdk&sort=score+desc%2C+metadata_modified+desc

![download-2](https://user-images.githubusercontent.com/26583461/93630752-7cb8b580-f9b8-11ea-92cd-89578f328575.png)

**Comment by J-bytes** [comment]
Correction appliqué

**Comment by alexaantoniazzi** [comment]
Correction validée
