### ISSUE TITLE
Corrections No. 38 -  [langue]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#24]
En français, il faut traduire Data Explorer en bas des fiches.

Voir http://13.88.240.170:8080/fr/dataset/06f5e364-6e2c-4d1c-95c2-9fb7d871ca20/resource/6087f154-9dab-4b49-9247-ef4f60d42994 il est écrit Data Explorer

![download-3](https://user-images.githubusercontent.com/26583461/93630866-b2f63500-f9b8-11ea-98f0-48d018d9e5da.png)

**Comment by J-bytes** [comment]
Ce probème semble provenir de l'extension reclineview (intégré à ckan) qui ne serait pas ben traduite

**Comment by J-bytes** [comment]
https://github.com/ckan/ckan/issues/5732

**Comment by nfee006** [comment]
Closing this because it is a duplicate of https://github.com/asc-csa/ckanext-asc-csa/issues/58
