### ISSUE TITLE
Corrections No. 39 – [langue]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#25]
En français, il faudrait avoir la mention (en anglais seulement) après tous les liens vers des sites anglophones (surtout dans les fiches, sous Informations additionnelles, à côté du titre URL de la page d'accueil et/ou ailleurs), exemple: http://13.88.249.89:8080/fr/dataset/cloudsat

Idem s’il existe des liens menant vers des sites uniquement francophones. Ceux-ci doivent être suivis de « (French only) ».

![download-4](https://user-images.githubusercontent.com/26583461/93630921-cd301300-f9b8-11ea-9765-9744c022ff05.png)

**Comment by J-bytes** [comment]
À corriger manuellement pour chaque entrée problématique

**Comment by J-bytes** [comment]
A new preset "link_language" has to be set and all dataset should then be manually checked for the languages of the links

**Comment by nfee006** [comment]
Implemented on @ data. Manual updates ongoing.

**Comment by nfee006** [comment]
Manual updates completed on @ data.
