### ISSUE TITLE
Corrections No. 40 – [validation HTML]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#26]
Deux langues, si je passe la validation HTML sur la page qui liste les jeux de données, ça me donne des erreurs d'ouverture et fermeture HTML

Error: Saw a form start tag, but there was already an active form element. Nested forms are not allowed. Ignoring the tag.

Error: End tag form seen, but there were open elements.

Error: Unclosed element div.

**Comment by J-bytes** [comment]
![image](https://user-images.githubusercontent.com/60334318/95783070-1107f680-0c9f-11eb-8f30-b6f8c390f3c4.png)

Certains avertissements sont affichés toutefois aucune errreur n'est reporté et ce dans les deux langues. 

![image](https://user-images.githubusercontent.com/60334318/95783387-b58a3880-0c9f-11eb-91d2-cd1930d11073.png)

**Comment by nfee006** [comment]
Closing this because it is a duplicate of https://github.com/asc-csa/ckanext-asc-csa/issues/80 and has been addressed.
