### ISSUE TITLE
Corrections No. 41 - [validation HTML]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#27]
Fiche individuelle exemple http://13.88.249.89:8080/dataset/221c1c75-4c42-4286-a4ce-ca6c3027b7fe, validation HTML donne ces erreurs:

Voir http://13.88.240.170:8080/dataset/221c1c75-4c42-4286-a4ce-ca6c3027b7fe

Plusieurs erreurs de tag br, voici un exemple:

Error: End tag br.

From line 1173, column 13; to line 1173, column 17

**Comment by J-bytes** [comment]
La validation html fut effectué. Il est à noté que si l'option "page web, html uniquement" est sélectionné,  un résultat différent peut être obtenu

**Comment by nfee006** [comment]
W3 now only flags the following (js type warning):
![image](https://user-images.githubusercontent.com/11013061/106950662-ba667280-66fc-11eb-8fdc-72ab2466919d.png)

This will not be addressed as it would require edits to vanilla CKAN. It is a warning based on HTML5 standards and not an error.
