### ISSUE TITLE
Corrections No. 42 - [Validation HTML]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#28]
Le code HTML ne passe pas la validation (https://validator.w3.org/)
Voir : http://13.88.240.170:8080/fr/dataset

**Comment by J-bytes** [comment]
Les résultats du validateur varie selon qu'on télécharge la page en entier ou juste le html. J'assumerai que le résultat le plus proche de la réalité est celui de la page téléchargé au complet. Ce sont donc ces erreurs qui seront vérifiés.

**Comment by J-bytes** [comment]
Atttention : Le résultat de w3 varie selon que la page html soit téléchargé "au complet" ou seulement le html

**Comment by J-bytes** [comment]
Correction (très) partiel appliqué. Plusieurs de ces changements devraient être appliqués directement dans  le développement de ckan

**Comment by J-bytes** [comment]
![image](https://user-images.githubusercontent.com/60334318/94999439-6f3e2680-0587-11eb-8e98-91106611d06a.png)

**Comment by J-bytes** [comment]
La validation est presque complétée

**Comment by J-bytes** [comment]
validation terminée. Elle n'est pas encore complètement poussée sur le serveur test

**Comment by nfee006** [comment]
Checked with W3 - both URL and file upload. Only javascript type attribute warnings remain:

![image](https://user-images.githubusercontent.com/11013061/107078305-21972c00-67bc-11eb-8047-c771828cbb63.png)

This will not be addressed as it would require edits to vanilla CKAN. It is a warning based on HTML5 standards and not an error.
