### ISSUE TITLE
Corrections No. 44 [Langues]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#30]
Le libellé du bouton « Go » devrait être plus représentatif que « Go », par exemple « Trier »

Voir : http://13.88.240.170:8080/fr/dataset

![download-6](https://user-images.githubusercontent.com/26583461/93631197-2a2bc900-f9b9-11ea-9605-f02685c757ec.png)

**Comment by J-bytes** [comment]
correction appliqué

**Comment by alexaantoniazzi** [comment]
Correction validée
