### ISSUE TITLE
Corrections No. 51 [Langue]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#37]
http://data.asc-csa.gc.ca:8080/fr/dataset/bfb2331e-6d68-41c0-8cf4-c2e9c4d68eb7  

En français, sur les fiches, le titre de la boîte « À propos de ce site » devrait plutôt dire « À propos de cette fiche » pour être cohérent avec l’anglais.

![download-13](https://user-images.githubusercontent.com/26583461/93631564-d1106500-f9b9-11ea-873e-3eaf1c41752b.png)

**Comment by J-bytes** [comment]
Corrigé dans master

**Comment by alexaantoniazzi** [comment]
Correction validée
