### ISSUE TITLE
Corrections No. 52 [Langue]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#38]
http://data.asc-csa.gc.ca:8080/fr/dataset/a19446d3-2f74-4aea-85d3-33ed21d54850  

En français, le titre de la fiche « australie » devrait prendre une majuscule.

![download-14](https://user-images.githubusercontent.com/26583461/93631619-e7b6bc00-f9b9-11ea-85f8-eb6b8586bff9.png)

**Comment by J-bytes** [comment]
Cette erreur est située dans la métadonnée. Elle peut toutefois être corrigé manuellement après l'importation des données.

**Comment by alexaantoniazzi** [comment]
Fixed on @data

**Comment by nfee006** [comment]
Verified on @ data.
