### ISSUE TITLE
Corrections No. 53 [Typo]

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#39]
http://data.asc-csa.gc.ca:8080/fr/dataset/a19446d3-2f74-4aea-85d3-33ed21d54850  

En français, sous « Informations additionnelles », on devrait indiquer seulement «Courriel » ou « Personne-ressource » pour être cohérent avec l’anglais.

![thumbnail_image026](https://user-images.githubusercontent.com/26583461/93631772-28163a00-f9ba-11ea-9c5a-bdc706dd8fa6.jpg)

**Comment by J-bytes** [comment]
corrigé dans master

**Comment by alexaantoniazzi** [comment]
Correction validée
