### ISSUE TITLE
CKAN - Page Selection

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#48]
When on page 1: Number ordering skips 4

<img width="285" alt="Screen Shot 2020-10-07 at 2 55 02 PM" src="https://user-images.githubusercontent.com/26583461/95375224-51393480-08ad-11eb-8bb8-62f6743d20a7.png">

When on page 3:

<img width="420" alt="Screen Shot 2020-10-07 at 2 55 35 PM" src="https://user-images.githubusercontent.com/26583461/95375236-58604280-08ad-11eb-9492-777635a8c576.png">

**Comment by J-bytes** [comment]
this problem is based on the ckan app itself and not our extension.

**Comment by J-bytes** [comment]
resolved in ckan 2.8.6
