### ISSUE TITLE
CKAN - PDF download button leads to 502: Proxy Error on specified datasets

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#49]
Datasets: 

1. Evaluation of the STDP for the Period of 2002/03 to 2007/08
2. Management Action Plans Follow-Up for evaluation - Annual Report as of March 31, 2011
3. Evaluation of the RADARSAT-2 Major Crown Project
4. Annual Report of the External Members of the Audit Committee 2013-2014

**Comment by J-bytes** [comment]
Those links may just be dead... A good clean up of all the urls might be required. It could then be tempting to wait a bit and then just manually change/test every url.

**Comment by J-bytes** [comment]
Those links seems to work on open canada ... I'll check if they work on my version of ckan

**Comment by J-bytes** [comment]
@alexaantoniazzi  All links seems operationnal on my version of ckan ....

**Comment by alexaantoniazzi** [comment]
Could not replicate on server
