### ISSUE TITLE
Classement scientifique vrai/faux

### ISSUE THREAD

**Issue by J-bytes** [asc-csa/ckanext-asc-csa#50]
Le classement pour l'instant n'est pas parfait. Si un nettoyage des données manuelles est effectué, il serait alors très intéressant de venir corriger les erreurs possible de ce classement

**Comment by alexaantoniazzi** [comment]
changes made on @data

**Comment by nfee006** [comment]
Verified on @ data. Some datasets are slightly ambiguous so it may be helpful to devise a better system in the future.
