### ISSUE TITLE
Add missing datasets not hosted at CSA

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/ckanext-asc-csa#52]
Add datasets funded by CSA but not hosted at CSA

**Comment by J-bytes** [comment]
Let's not forget about the three missing datasets from the government of canada ckan instance. I sadly am not sure which one exactly is missing but due to problems out of our control, the harvester could not get them.

**Comment by nfee006** [comment]
NB J-Bytes comment is addressed in https://github.com/asc-csa/ckanext-asc-csa/issues/53.

**Comment by nfee006** [comment]
The open government team has confirmed that the dataset registry is complete at this time. This will, however, be something to keep in mind long-term. We will reopen the issue if need be.
