### ISSUE TITLE
Add an entry for UVIT on AstroSat

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/ckanext-asc-csa#55]
ASTROSAT Support Cell (http://astrosat-ssc.iucaa.in/?q=uvitData)

**Comment by nfee006** [comment]
A private dataset has been created. It will need approval from the Open Government team prior to publication. 

The dataset is called: "PLACEHOLDER-- UVIT on ASTROSAT". It has been populated with all available metadata.
