### ISSUE TITLE
No control over css

### ISSUE THREAD

**Issue by J-bytes** [asc-csa/ckanext-asc-csa#57]
Our version of ckan use https://wet-boew.github.io/themes-dist/GCWeb/css/theme.min.css as its css file. It means we have little control over changes we want to apply to it. There is a module (fanstatic) built into ckan to use local css files. It seems there were an attempt to use fanstatic before it was abandoned. For the future, having a css we can customize to our need could prove more than useful

**Comment by J-bytes** [comment]
The change has been made. However, we might need to apply some change to the local css files if we see changes that we do not want appearing. I will leave this issue open until I can get some feedback to make sure nothing got broken

**Comment by nfee006** [comment]
Closing this issue because nothing appears to have been broken by this change. We have successfully made CSS modifications using the local theme.min.css file.
