### ISSUE TITLE
ckanext-recline_view missing many translations

### ISSUE THREAD

**Issue by J-bytes** [asc-csa/ckanext-asc-csa#58]
![Screenshot 2020-11-21 145721](https://user-images.githubusercontent.com/60334318/99886382-0af42680-2c0a-11eb-9a41-a20d367a4b3f.png)
![Screenshot 2020-11-21 145957](https://user-images.githubusercontent.com/60334318/99886406-3d058880-2c0a-11eb-9d43-1344ea406aff.png)

**Comment by J-bytes** [comment]
We've received the following message before the ckan issue was closed :

@J-bytes Besides the "Data Explorer" string which is in CKAN, all the other ones are rendered by the Recline JS library, which doesn't support i18n yet.
Original issue is datopian/recline#459
In case you can help, there is an old PR (datopian/recline#508) that might be easy to bring up to speed with Recline's master, and perhaps the folks at datopian can merge it and release a new recline version. I'd be happy to upgrade the one shipped with CKAN at that point

Alternatively, just for table views there's another view plugin shipped with CKAN, datatables_view that might have better i18n support.

**Comment by J-bytes** [comment]
To support bilingual preview of the data we will therefore need to do a three step process :

1. update datopian/recline#508 to bring it in line with the master 

2. submit it to the datopian team to merge it with master

3. Submit this new version of recline to ckan in order to push it to a future update

**Comment by nfee006** [comment]
As an stopgap measure, this text can be manually modified in the following files:

"Data Explorer" at the top of the page
https://github.com/ckan/ckan/blob/d2dbcd3a6c380503398823e170d5ea2050a54b9e/ckanext/reclineview/plugin.py
![image](https://user-images.githubusercontent.com/11013061/101806616-07491680-3ac9-11eb-9c9d-835c9efc3f9a.png)

All other text
https://github.com/ckan/ckan/blob/aa32b2379a5b2e52d3c95e4e985719f70a3bd0d5/ckanext/reclineview/theme/public/vendor/recline/recline.js
![image](https://user-images.githubusercontent.com/11013061/101806886-5abb6480-3ac9-11eb-8b2c-66507b88ae00.png)

**Comment by nfee006** [comment]
NB. this correction is only partial. Changing the "Data Explorer" text itself causes critical errors on @ data. This is likely because of how this text interacts with the resource_view table in the postgres database. 

As such, this specific change has been reverted on @ data. Every element that could be translated without critical errors has been changed.

**Comment by dreneuw** [comment]
Attempt at solving this issue:

The following was attempted on a local installation:
> As an stopgap measure, this text can be manually modified in the following files:
> 
> "Data Explorer" at the top of the page
> https://github.com/ckan/ckan/blob/d2dbcd3a6c380503398823e170d5ea2050a54b9e/ckanext/reclineview/plugin.py
> ![image](https://user-images.githubusercontent.com/11013061/101806616-07491680-3ac9-11eb-9c9d-835c9efc3f9a.png)

This resulted in the same issues as mentioned above. It was investigated that maybe the french translation was missing or was incorrectly linked but the correct translation is found at:
ckan\ckanext\csa\i18n\fr\LC_MESSAGES
And:
ckanext-asc-csa\ckanext\csa\i18n\fr\LC_MESSAGES
It does not seem that it is incorrectly linked as other translations from those files appear. It may be interesting to investigate if the fact that there are two translation files causes issues.
There was an attempt to find the variable reference in the html template file of the data preview page but it could not be found

**Comment by nfee006** [comment]
This was addressed by https://github.com/asc-csa/ckanext-asc-csa/commit/86e59e508cf95f8b6d77677497ac827865153778 as well as local edits to the recline.js file in vanilla CKAN (https://github.com/ckan/ckan/blob/aa32b2379a5b2e52d3c95e4e985719f70a3bd0d5/ckanext/reclineview/theme/public/vendor/recline/recline.js). This edited recline.js file will be uploaded to livelink and made available on github.  

![image](https://user-images.githubusercontent.com/11013061/107967331-f90cf000-6f7a-11eb-97f7-ea6e58500f98.png)

![image](https://user-images.githubusercontent.com/11013061/107967371-04f8b200-6f7b-11eb-9c51-fb6598a5a840.png)
