### ISSUE TITLE
Data_proxy not working

### ISSUE THREAD

**Issue by J-bytes** [asc-csa/ckanext-asc-csa#59]
Data proxy seems to require a public ip address or ckan. We can avoid using it by using resource_proxy. Simply add resource_proxy to the plugins list in the ckan config file. This combine to a good usage of datapusher should enable the preview functionnality

**Comment by J-bytes** [comment]
A double check on somebody else's  ckan installation will be required to move forward. Once this is done, simply adding resource_proxy to the list of ckans.plugins in the configuration file should be enough

**Comment by nfee006** [comment]
@J-bytes resource_proxy added to the plugin list on development.ini on my VM. Unable to visualize a csv from @ data. I tried the link with both http and https. Am I missing something?

![image](https://user-images.githubusercontent.com/11013061/101643618-4fe9cc80-3a02-11eb-85df-94a61eb20a72.png)

**Comment by J-bytes** [comment]
@nfee006 when you created the dataset , was datapusher running ? If not , simply running it and changing the url ( when a new url is detected , datapusher re-fetch the data so changing it to a fake url and changing it back will do the trick) should do the trick . If however datapusher was running, I would need to dig deeper to find the root of the issue

**Comment by alexaantoniazzi** [comment]
Reimported all the data with datapusher running and getting the same error as Natasha.

**Comment by nfee006** [comment]
@J-bytes Datapusher was running but I restarted CKAN and Datapusher & recreated the dataset just in case. I did realize that I was running an outdated version of ckanext-asc-csa so I I updated that. Still getting this. Maybe it's a firewall issue? I guess it's working on Citrix for you?

What file did you edit to add that warning by the way? It doesn't seem to translate. 

![image](https://user-images.githubusercontent.com/11013061/101653619-81b46080-3a0d-11eb-86b8-f3dff06a2e4c.png)

**Comment by J-bytes** [comment]
Translation are not handled in a file by file basis. See https://docs.ckan.org/en/2.8/extensions/translating-extensions.html . Translation are added to the .po file. I've suggested to wait until we do new releases to push to the server to review new translations. If needed I can do the translation today ( "@" me if necessary)

**Comment by J-bytes** [comment]
Also, are urls to the data server publicly accessible or only internally through the vpn? If so, I would expect the links only to work on the server and not on our local VM

**Comment by nfee006** [comment]
@ data is only accessible via the VPN right now (my understanding) but my VM has access to the CSA network. I'm able to view those files if I go to the link directly.

**Comment by J-bytes** [comment]
You are then officially further then I've ever been on the development of the visualisation as my VM can't access the VPN. Did you tried creating a dud datasets with some public facing csv file from another source? I had tried it and it seemed to work with another source of data. Try replicating this so we can pinpoint the error.

**Comment by nfee006** [comment]
Works fine with any public csv. It always has though on my side.

**Comment by J-bytes** [comment]
when you loaded the data did the datapusher's console report any error?

**Comment by nfee006** [comment]
I have a sneaking suspicion that there may be something wrong with CKAN on my VM. I'll email you once I figure this out. Thanks!

**Comment by nfee006** [comment]
I think there might be something wrong with how data is stored and/or retrieved on/from the datastore. If you compare the output from https://demo.ckan.org/api/3/action/datastore_search?resource_id=_table_metadata to the same call on @ data, there is clearly something off. I get the same output as @data on my VM CKAN as well.

Resource_proxy has been added to the plugin list on @ data.

**Comment by nfee006** [comment]
Resolved on @ data. The solution was to avoid using either - we fixed SSL certificate issues in datapusher, allowing us to use the datastore instead of a proxy.
