### ISSUE TITLE
Metdata - Homepage URL - @data 

### ISSUE THREAD

**Issue by alexaantoniazzi** [asc-csa/ckanext-asc-csa#61]
RADARSAT-1 Australia: http://13.88.240.170:8080/dataset/a19446d3-2f74-4aea-85d3-33ed21d54850
RADARSAT-1 Antarctica: http://13.88.240.170:8080/dataset/38ce99e4-8c60-45cc-ba88-7edc9822fd99​

![Screen Shot 2020-12-07 at 12 08 42 PM](https://user-images.githubusercontent.com/26583461/101398986-df756b00-389c-11eb-97a4-913b7fa3d7fe.png)

The link does not format into the available space or become a hyperlink. The link worked for other RADARSAT-1 projects, just not on those two.

**Comment by nfee006** [comment]
Verified. Fixed by Alexa on @ data.
