### ISSUE TITLE
Organization facet labels not working 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#63]
The facets on the /organization page are not properly configured. Not clear if we even need this page though considering we are only handling data from one organization.   

![image](https://user-images.githubusercontent.com/11013061/101639455-532e8980-39fd-11eb-8c28-449b6908a2f0.png)

**Comment by J-bytes** [comment]
The access to this page could be removed. The user have no use for those pages (it would be simple to redirect the urls from those page to the 404 page or the dataset page. Otherwise since they are not linked from anywhere even as is I do not expect this to be much of an issue

**Comment by J-bytes** [comment]
@nfee006 @low-decarie let me know the solution you prefer and I'll implement it shortly

**Comment by nfee006** [comment]
I think we're fine leaving it as it is for now. Thanks @J-bytes
