### ISSUE TITLE
Relabeling science_admin in the dataset facet

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#64]
Change the "Scientific Data" value labels from True or False to Science or Management/Operations on @ data. 

Editing the ckan_dataset.js page does not appear to solve this issue. 

![image](https://user-images.githubusercontent.com/11013061/102120931-346f2f00-3e11-11eb-9e33-632b9c1af171.png)

**Comment by J-bytes** [comment]
@nfee006 A soluton has been pushed to master. I'll let you close the issue if you are satisfied with the results

**Comment by nfee006** [comment]
Implemented in master and on @ data. One issue: "Data category" does not translate properly. It likely needs to be set in one of the babel files.

**Comment by nfee006** [comment]
Successfully implemented on @ data.
