### ISSUE TITLE
40. standard web - correct search page html issues 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#80]
40. [standard web]
Deux langues, si je passe la validation html sur la page qui liste les jeux de données, ça me donne des erreurs d'ouverture et fermeture html
Il y a encore des erreurs de tag form qui s'ouvre dans un form déjà ouvert et un div qui ne se ferme pas.

ex.  <form> pour le dropdown « Trier ». Ce form est à l’intérieur d’un autre form (nested form), non-permis en HTML. Le HTML ne valide pas.

**Comment by dreneuw** [comment]
a3c4668c0ffbc9e38d3362458b6989531b2597b7 fixes this issue by adding a closing tag to the form element (</form>). This still needs to be tested on the production server.

**Comment by nfee006** [comment]
Addressed by https://github.com/asc-csa/ckanext-asc-csa/commit/a3c4668c0ffbc9e38d3362458b6989531b2597b7,  https://github.com/asc-csa/ckanext-asc-csa/commit/0330da75759d0fbddd60a0d1d739ad451fd2bd35, and https://github.com/asc-csa/ckanext-asc-csa/commit/ad5616a585390386511c122e431b4d62b814f7f5.

W3 now only flags the following:
![image](https://user-images.githubusercontent.com/11013061/106950662-ba667280-66fc-11eb-8fdc-72ab2466919d.png)

This will not be addressed as it would require edits to vanilla CKAN. It is a warning based on HTML5 standards and not an error.
