### ISSUE TITLE
Internal Server Error when creating new database.

### ISSUE THREAD

**Issue by dreneuw** [asc-csa/ckanext-asc-csa#85]
Internal Server Error encountered when attempting to create a new database.
Occurred when manually transferring the Risk profile (OID-2018-00281) database from DIIDS to data.asc-csa.gc.ca. This was done on Internet Explorer through a Citrix environment.
The error occurred after pressing the button below:
![image](https://user-images.githubusercontent.com/56747050/105769213-7bc9fe80-5f2b-11eb-83c4-f294468e790b.png)

Below is all the information filled on the database creation page: 
![image](https://user-images.githubusercontent.com/56747050/105769093-4b826000-5f2b-11eb-96d4-b18537e9a4d4.png)
![image](https://user-images.githubusercontent.com/56747050/105769307-a3b96200-5f2b-11eb-953c-b74dd0445fc8.png)
![image](https://user-images.githubusercontent.com/56747050/105769360-b59b0500-5f2b-11eb-8930-d7147e816293.png)
![image](https://user-images.githubusercontent.com/56747050/105769390-c0559a00-5f2b-11eb-9c68-b0d8704be68a.png)
![image](https://user-images.githubusercontent.com/56747050/105769418-c9466b80-5f2b-11eb-916c-f97422ccf999.png)
![image](https://user-images.githubusercontent.com/56747050/105769447-d2373d00-5f2b-11eb-9a64-11f1648a5c2a.png)
![image](https://user-images.githubusercontent.com/56747050/105769482-dcf1d200-5f2b-11eb-8a40-c3aa36cd281d.png)
![image](https://user-images.githubusercontent.com/56747050/105769504-ea0ec100-5f2b-11eb-8dcf-0d9a259e729c.png)
![image](https://user-images.githubusercontent.com/56747050/105769619-14f91500-5f2c-11eb-9dc1-7763e001734a.png)
![image](https://user-images.githubusercontent.com/56747050/105769704-34903d80-5f2c-11eb-823a-b15979e1d8bb.png)
![image](https://user-images.githubusercontent.com/56747050/105769748-47a30d80-5f2c-11eb-9dfd-b4afca3dd8bd.png)

**Comment by nfee006** [comment]
Tentatively addressed server-side. Will need to monitor.

**Comment by nfee006** [comment]
Marking as resolved because the issue has not reappeared in past day.
