### ISSUE TITLE
Upgrade to CKAN 2.9

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#90]
Including all necessary changes including refactoring to Python 3.

**Comment by nfee006** [comment]
**Considerations**

- Python 2 elements will need to be recoded in Python 3
- This will require a database upgrade 
- It is recommended that we upgrade the solr schema 
- All metadata from the existing portal will need to be transferred
- “Implementation of an organization structure that reflects the CSA organization structure”
- We need to ensure that our ancillary tools will continue to work, including:
  -  Datapusher (see https://github.com/ckan/ckan/issues/5536)
  - https://github.com/asc-csa/ckan-gov-canada-harvester-master 
- We also need to make sure that our vanilla CKAN customizations are carried over, including but not limited to: 
   - The translations on the Data Explorer page https://github.com/asc-csa/ckanext-asc-csa/issues/58
   - Alt-text on the Data Explorer page https://github.com/asc-csa/ckanext-asc-csa/issues/19 
   - Pagination navigator accessibility https://github.com/asc-csa/ckanext-asc-csa/issues/31

https://docs.ckan.org/en/2.9/changelog.html

**Comment by nfee006** [comment]
@coleweusthem had you seen this?

**Comment by coleweusthem** [comment]
@nfee006, I don't believe I had. Thanks for flagging it.

**Comment by nfee006** [comment]
FYI for when migrating to Ubuntu 20.04 

https://github.com/ckan/ckan/issues/5919#issuecomment-849733312

Doesn't matter too much if we use tomcat or jetty though.

**Comment by coleweusthem** [comment]
I've been using tomcat9 as it's what the CKAN docs were recommending

**Comment by nfee006** [comment]
Perfect - that's what I have too.
