### ISSUE TITLE
7) [Standard web + Accessibilité] Correct header order 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#91]
"Pour la page de recherche ET de détails d’un jeu de donnée, le H1 doit être un des premiers éléments après l’ouverture de la balise <main>, de façon à englober tout le contenu qu’il dessert, donc tout ce qui se trouve après. Le H1 doit être le titre de toute la page, et non uniquement d’une portion du contenu. Il peut être statique et générique (« Jeux de données ») ou être un peu plus spécifique. De quels jeux de données s’agit-il? Le nombre de résultats de recherche peut rester à cet endroit, mais doit devenir un h2."

H1, if they appear, are doing so too far down the page.

**Comment by coleweusthem** [comment]
Investigating this

**Comment by coleweusthem** [comment]
I'm unable to find an occurrence of this issue so I'm closing this issue. If an occurrence is found please provide an example and reopen.

**Comment by nfee006** [comment]
Does this clarify at all? 
"For the search page and the dataset detail pages, the H1 must be one of the first elements after opening <main>, in order to encompass all of the content on the page. The H1 must be the title of the entire page and not only a part of the content. It can be static and generic (« datasets ») or be a little more specific. Which dataset does it refer to? The number of search results can stay in the same spot but must become an H2."

**Comment by nfee006** [comment]
@coleweusthem 
Inspiration from the Government-wide portal https://search.open.canada.ca/en/od/?od-search-subjects=Agriculture&_ga=2.5206451.1274975115.1614954864-797425555.1606752517

**Search page** 
CSA Open Government Portal / Portail du gouvernement ouvert de L'ASC
![image](https://user-images.githubusercontent.com/11013061/110130367-ebd36c00-7d96-11eb-9786-c295d53ddcb3.png)

![image](https://user-images.githubusercontent.com/11013061/110129875-6fd92400-7d96-11eb-950e-4c19e417f1a8.png)


**Dataset page** 
Would it be possible to grab the existing H1 (dataset name) and put it right after `main` and above "Additional Information" as well? Taken from https://data.asc-csa.gc.ca/dataset/ef42819f-35bb-49c0-a368-1e61fa876ee6 
![image](https://user-images.githubusercontent.com/11013061/110130957-a06d8d80-7d97-11eb-9869-e43ccd46e21f.png)

**Comment by coleweusthem** [comment]
Thanks for the additional info. I'll look into rearranging as you had suggested.

**Comment by nfee006** [comment]
@coleweusthem 

In a similar vein, would it be possible to change the breadcrumbs so that they reflect these H1 please? I can create a new issue if need be. 

Instead of Open Data/Données ouvertes -> Open Government/Gouvernement ouvert

**Comment by coleweusthem** [comment]
I was reviewing the policy, and the better solution may be to shift the "main" role to the element with the h1 in it. The role is meant to highlight the main content on the page to screen readers and similar tools. Currently it seems to wrapping everything not in the header and footer. I would consider the area with the h1 currently the main content, or at least the area below the breadcrumb. If that makes sense with you I can implement that instead.

**Comment by coleweusthem** [comment]
And to clarify for the breadcrumbs you would want for the example above to read 'Canada.ca / Canadian Space Agency / Open Data / MOPIT - Measurements of Pollution in the Troposphere'? I'm currently figuring out how to make it happen.

**Comment by nfee006** [comment]
> I was reviewing the policy, and the better solution may be to shift the "main" role to the element with the h1 in it. The role is meant to highlight the main content on the page to screen readers and similar tools. Currently it seems to wrapping everything not in the header and footer. I would consider the area with the h1 currently the main content, or at least the area below the breadcrumb. If that makes sense with you I can implement that instead.

If you think that's in-line with the policy then go for it (could you provide a link so I can forward to comms please?). I still think it would make the most sense to change the H1 on the search page to "CSA Open Government Portal / Portail du gouvernement ouvert de L'ASC" since the number of datasets found is not particularly descriptive. Your fix would be suitable for the dataset page though I believe. 


> And to clarify for the breadcrumbs you would want for the example above to read 'Canada.ca / Canadian Space Agency / Open Data / MOPIT - Measurements of Pollution in the Troposphere'? I'm currently figuring out how to make it happen.

Ideally yes (though please replace Open Data with Open Government). This commit might be useful if you're trying to get the translated dataset name: https://github.com/asc-csa/ckanext-asc-csa/commit/cf05413ea40152cd200f2c503444a5ecc71f3e87

**Comment by coleweusthem** [comment]
I'll move the header on the search page then. Here are the links:
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/main.html
https://www.w3.org/TR/wai-aria-1.0/roles#main

And thanks for that commit, thats what I'm trying to figure out so that may speed things up.

**Comment by nfee006** [comment]
Addressed by https://github.com/asc-csa/ckanext-asc-csa/pull/102 and merged into master.
