### ISSUE TITLE
9) [Accessibilité] Fix the API page  

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#93]
"Pour la page de l’API (https://data.asc-csa.gc.ca/fr/API), si le `<aside>` est vide, le contenu doit être complètement à gauche, il ne doit pas y avoir un espace vide."

For the API page (https://data.asc-csa.gc.ca/fr/API), if the `<aside>` is empty, the content must be completely to the left. There should not be any blank space.

**Comment by nfee006** [comment]
Addressed by https://github.com/asc-csa/ckanext-asc-csa/commit/c0d5684901afdc6d8b3a0298d0d140498fec302d

**Comment by nfee006** [comment]
Breadcrumbs are missing. This needs to be fixed. 
![image](https://user-images.githubusercontent.com/11013061/109701667-44b9bf00-7b61-11eb-8472-63a9d9ed7641.png)

**Comment by coleweusthem** [comment]
Closing as pull request to solve was merged
