### ISSUE TITLE
W3 validator - all pages

### ISSUE THREAD

**Issue by nfee006** [asc-csa/ckanext-asc-csa#96]
All pages must pass the W3 validator without any errors. https://validator.w3.org/

**Comment by nfee006** [comment]
I am currently working on addressing the issues in the header/footer.

**Comment by nfee006** [comment]
One error remains, caused by https://www.international.gc.ca/world-monde/index.aspx?lang=eng in the header. I’ve tried encoding the equals sign differently (%3d) but that did not help.
![image](https://user-images.githubusercontent.com/11013061/109701339-e391eb80-7b60-11eb-921e-597d9f0bc8a9.png)

Several warnings remain but it’s not clear if these can be fixed without making changes to vanilla CKAN. N.B the header warning only appears on the Data Explorer page. 
![image](https://user-images.githubusercontent.com/11013061/109701422-fad0d900-7b60-11eb-81d3-08c4b528a11e.png)

**Comment by coleweusthem** [comment]
Investigating

**Comment by coleweusthem** [comment]
Closed pending review of solution
